AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: bskylog

Parameters:
  SiteDomainName:
    Type: String
  Certificate:
    Type: String
  CloudFrontManagedCachePolicy:
    Type: String
    Default: "658327ea-f89d-4fab-a63d-7e88639e58f6"
  HandleIndex:
    Type: String
    Default: HandleIndex
  BskyHost:
    Type: String
    Default: "https://bsky.social"

Globals:
  Function:
    Runtime: provided.al2023
    Handler: bootstrap
    Architectures:
      - x86_64

Resources:
  PublishBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false

  PublishBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PublishBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${PublishBucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Ref AWS::StackName
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        DefaultRootObject: index.html
        Aliases:
          - !Ref SiteDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          CachePolicyId: !Ref CloudFrontManagedCachePolicy
          TargetOriginId: !Sub "s3-${PublishBucket}"
          ViewerProtocolPolicy: https-only
          AllowedMethods:
            - GET
            - HEAD
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
          - Id: !Sub "s3-${PublishBucket}"
            DomainName: !GetAtt PublishBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
            S3OriginConfig: {}

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Did
          AttributeType: S
        - AttributeName: Handle
          AttributeType: S
      KeySchema:
        - AttributeName: Did
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Ref HandleIndex
          KeySchema:
            - AttributeName: Handle
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  CrawlerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Did
          AttributeType: S
      KeySchema:
        - AttributeName: Did
          KeyType: HASH

  CrawlerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      PackageType: Zip
      CodeUri: crawler/
      Timeout: 900
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          BUCKET: !Ref PublishBucket
          DISTRIBUTION: !Ref Distribution
          CRAWLER_TABLE: !Ref CrawlerTable
          BSKY_HOST: !Ref BskyHost

  CrawlerFunctionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CrawlerFunctionPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:Scan
            Resource:
              - !GetAtt CrawlerTable.Arn
          - Effect: Allow
            Action:
              - cloudfront:CreateInvalidation
            Resource:
              - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution}"
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListObjects
              - s3:ListObjectsV2
            Resource:
              - !Sub "arn:aws:s3:::${PublishBucket}/did:*"
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${PublishBucket}"
      Roles:
        - !Ref CrawlerFunctionRole

Outputs:
  PublishBucket:
    Value: !Ref PublishBucket
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
  Distribution:
    Value: !Ref Distribution
  UserTable:
    Value: !Ref UserTable
  CrawlerTable:
    Value: !Ref CrawlerTable
  CrawlerFunction:
    Value: !Ref CrawlerFunction
